include: package:lints/recommended.yaml

analyzer:
  strong-mode:
    implicit-casts: false

linter:
  rules:
    - always_declare_return_types
    - directives_ordering
    - lines_longer_than_80_chars
    - public_member_api_docs
    - slash_for_doc_comments
    - unnecessary_const
    - unnecessary_new
