name: test_reflective_loader
version: 0.1.7

description: Support for discovering tests and test suites using reflection.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/test_reflective_loader

environment:
  sdk: '>=1.8.0 <3.0.0'

dependencies:
  test: '>=0.12.0 <2.0.0'
