name: Dart

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # “At 00:00 (UTC) on Sunday.”
    - cron: '0 0 * * 0'

env:
  PUB_ENVIRONMENT: bot.github

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: dev

      - name: pub get
        run: dart pub get

      - name: dart format
        run: dart format --output=none --set-exit-if-changed .

      - name: dart analyze
        run: dart analyze

      - name: dart test
        run: dart test
